# Generated by Django 3.1.7 on 2021-11-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_dcx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction_logs',
            name='ask',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prediction_logs',
            name='bid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prediction_logs',
            name='high',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prediction_logs',
            name='last_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prediction_logs',
            name='low',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
